### ISSUE TITLE
IntelliJ 2020.2 compatibility

### ISSUE THREAD

**Issue by krasa** [anthraxx/intellij-awesome-console#56] opened 2020-05-31 17:01 UTC
ConsoleFilterProvider is now called for every line, I recommend using ConsoleDependentFilterProvider and cache AwesomeLinkFilter instance per console.

**Comment by anthraxx** [comment] 2020-06-05 18:37
thanks for the hint, thats a good idea

**Comment by olivernybroe** [comment] 2020-09-16 07:28
Experiencing this problem also. Makes the terminal really slow and lagging a lot in PhpStorm 2020.2

**Comment by anthraxx** [comment] 2020-09-16 09:09
I will release an update latest this weekend, sorry for the delay

**Comment by olivernybroe** [comment] 2020-09-16 10:39
@anthraxx No problem. Just wanted to point out how the issue looks like in case users google it, so this will show as a hit.

Thanks for the awesome work!

**Comment by anthraxx** [comment] 2020-09-17 16:47
fixed in a6d2a001ea9e88c0f85f798e673dc0d38b10d797 and 73f77e9292dd7c1c06db5ffdfb3eb2d74bb79cca
release will follow

**Closed by anthraxx** 2020-09-17 16:47 UTC

**Comment by anthraxx** [comment] 2020-09-22 22:13
@olivernybroe an update has been released and should arrive in the marketplace.

PS: I would be incredibly happy to get some ratings in the jetbrains marketplace. Lately it seems nobody gives any rating except if after happily using the plugin for years free of charge and in latest intellij 2020.2 update a performance regression with the terminal arrives, then instant going to the rating and giving 1 star, which is super demotivating for a free project :crying_cat_face:

**Comment by olivernybroe** [comment] 2020-09-22 22:17
Awesome! Thanks!

Aww that sucks... I have a couple of IntelliJ plugins myself and getting ratings are the hardest ever. I'll for sure rate it up (gonna do it tomorrow)

**Comment by anthraxx** [comment] 2020-09-25 12:15
@olivernybroe I very much appreciate your replies and rating on the JetBrains page :heart: thanks, that's huge :cat:
