### ISSUE TITLE
Navigation to line sometimes incorrect - does not account for folded lines

### ISSUE THREAD

**Issue by dmeibusch** [anthraxx/intellij-awesome-console#79] opened 2021-03-29 23:13 UTC
Awesome plugin, thank you.

Navigating to a line does not take into account any folded (https://www.jetbrains.com/help/idea/code-folding-settings.html) lines above.

Workaround:  Expand all folded text in the file before clicking on the link. Code | Folding | Expand All.

This issue might also account for some other issues that indicate unknown "inconsistent" behaviour. 

Intellij 20.3.3
Awesome Console 0.1337.11

**Comment by anthraxx** [comment] 2021-03-29 23:31
Duplicate of #75
If you have a intellij API idea, feel free to point out. The navigation API's do not support "raw" line numbers.

**Comment by dmeibusch** [comment] 2021-03-30 03:21
Ah, I missed the #75 duplicate - I was only looking at closed issues. My bad. I haven't used the navigation APIs, however ever I do recall the same issues when I was working with the Eclipse API equivalents. :-(

**Comment by jlous** [comment] 2021-04-08 06:54
@anthraxx Could Editor.logicalToVisualPosition or offsetToVisualLine be helpful for calculating the correct line to move to?

**Comment by anthraxx** [comment] 2022-04-14 17:54
Fixed by 38e16d3655097dfcfd52fe1e7ec5b778f83b5e76

**Closed by anthraxx** 2022-04-14 17:54 UTC
